# Generated by Django 5.2 on 2025-06-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ("borrow_date",)},
        ),
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="check_actual_date",
        ),
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="check_expected_date",
        ),
    ]
